# Generated by Django 3.0.8 on 2020-07-05 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 5, 6, 41, 49, 139589, tzinfo=utc), verbose_name='Дата события'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 5, 6, 42, 2, 824724, tzinfo=utc), verbose_name='Время события'),
            preserve_default=False,
        ),
    ]
