# Generated by Django 3.0.8 on 2020-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='link',
            field=models.TextField(max_length=200, verbose_name='Ссылка на плейлист или видео'),
        ),
    ]
