# Generated by Django 3.0.8 on 2020-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20200703_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='link',
            field=models.TextField(verbose_name='Ссылка на плейлист или видео'),
        ),
    ]
