# Generated by Django 3.0.8 on 2020-07-04 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='time',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 4, 2, 46, 46, 854938, tzinfo=utc), verbose_name='Дата события'),
            preserve_default=False,
        ),
    ]
