# Generated by Django 3.0.8 on 2020-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='short_name',
            field=models.IntegerField(choices=[(0, 'пн'), (1, 'вт'), (2, 'ср'), (3, 'чт'), (4, 'пт'), (5, 'сб'), (6, 'вс')], verbose_name='Краткие названия'),
        ),
    ]
