# Generated by Django 3.0.8 on 2020-07-03 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0002_auto_20200703_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='My Schedule', max_length=50, verbose_name='Название расписания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsFriday', to='schedules.Schedule', verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsMonday', to='schedules.Schedule', verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsSaturday', to='schedules.Schedule', verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsSunday', to='schedules.Schedule', verbose_name='Воскресение'),
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsThursday', to='schedules.Schedule', verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsTuesday', to='schedules.Schedule', verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='usersschedule',
            name='wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsWednesday', to='schedules.Schedule', verbose_name='Среда'),
        ),
    ]
