# Generated by Django 3.0.8 on 2020-07-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20200704_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=150, verbose_name='Описание'),
        ),
    ]
