# Generated by Django 3.0.8 on 2020-07-04 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0003_auto_20200704_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название расписания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tasks', models.ManyToManyField(blank=True, related_name='weekendsAsTask', to='schedules.Task', verbose_name='Задачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание на неделю', 'verbose_name_plural': 'Расписания на неделю'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='UsersSchedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsFriday', to='schedules.DaySchedule', verbose_name='Пятница'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsMonday', to='schedules.DaySchedule', verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsSaturday', to='schedules.DaySchedule', verbose_name='Суббота'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsSunday', to='schedules.DaySchedule', verbose_name='Воскресение'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsThursday', to='schedules.DaySchedule', verbose_name='Четверг'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsTuesday', to='schedules.DaySchedule', verbose_name='Вторник'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduleAsWednesday', to='schedules.DaySchedule', verbose_name='Среда'),
        ),
    ]
